version: '3'

services:
  postgres:
    image: postgres:alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d
    env_file:
      - ./.env

  service:
    build: ./app
    restart: always
    volumes:
      - static_volume:/opt/app/static/
      - media_volume:/opt/app/media/
    env_file:
      - ./.env
    depends_on:
      - postgres

  nginx:
    image: nginx:latest
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./configs:/etc/nginx/conf.d:ro
      - ./data:/data/:ro
      - static_volume:/opt/app/static/
      - media_volume:/opt/app/media/
    depends_on:
      - service
    ports:
      - "80:80"
      - "8000:80"

  elasticsearch:
    image: elasticsearch:8.6.2
    restart: always
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    volumes:
      - elasticsearch_data:/opt/elasticsearch/data
    ports:
      - "9200:9200"
    env_file:
      - ./.env
    depends_on:
      - postgres
      - service

  etl:
    build: ./postgres_to_es
    restart: always
    env_file:
      - ./.env
    depends_on:
      - elasticsearch
      - postgres
      - service

volumes:
  postgres_data:
  elasticsearch_data:
  static_volume:
  media_volume:
